import Head from "next/head";
import styles from "../styles/Layout.module.scss";
import Header from "./Header";

const Layout = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Designo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <footer></footer>
    </div>
  );
};

export default Layout;
