import Head from "next/head";
import styles from "../styles/Layout.module.scss";
import Footer from "./Footer";
import Header from "./Header";

const Layout = ({ children }) => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Designo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/icons/favicon-32x32.png" />
        </Head>
        <Header />
        {children}
      </div>
      <Footer />
    </>
  );
};

export default Layout;
